-- +goose Up
CREATE TABLE posts (
  id UUID PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL UNIQUE,
  description VARCHAR NOT NULL,
  published_at VARCHAR NOT NULL,
  feed_id UUID REFERENCES feeds(id) NOT NULL ON DELETE CASCADE
);

-- +goose Down
DROP TABLE posts;